[tool.ruff]
line-length = 88
target-version = "py310"
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "ARG",  # flake8-unused-arguments
    "SIM",  # flake8-simplify
    "ERA",  # eradicate
    "PL",   # pylint
    "RUF",  # ruff-specific rules
]
ignore = []

[tool.ruff.per-file-ignores]
# Allow for `assert` statements and magic methods in tests
"tests/*" = ["S101", "PLR2004", "PLR0913"]

[tool.ruff.isort]
known-first-party = ["vanyba_telegramm"]
